// src/knowledgeBase.js
export const medicalKnowledgeBase = [
  {
    title: "Kiến Thức Y Khoa Cơ Bản",
    id: "co-ban",
    subitems: [
      { id: 'giai-phau-hoc', name: 'Giải Phẫu Học (Anatomy)', author: 'BS. Nguyễn Minh Khang', date: '12/10/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Nghiên cứu chi tiết về cấu trúc vật lý của cơ thể người, bao gồm hệ xương, cơ, các cơ quan nội tạng, hệ thần kinh, hệ tuần hoàn và tiêu hóa. Đây là môn học nền tảng, cung cấp bản đồ chi tiết về vị trí và mối liên hệ giữa các bộ phận.</p><h3>Lý giải & Ứng dụng</h3><p>Cung cấp "bản đồ" cho mọi can thiệp y khoa. Bác sĩ phẫu thuật cần hiểu rõ giải phẫu để thực hiện ca mổ chính xác, bác sĩ chẩn đoán hình ảnh dựa vào đó để đọc phim X-quang, CT-scan. Hiểu biết giải phẫu giúp xác định vị trí cơn đau và chẩn đoán bệnh lý liên quan.</p>` },
      { id: 'sinh-ly-hoc', name: 'Sinh Lý Học (Physiology)', author: 'TS. Lê Thị Thu Hà', date: '14/10/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Giải thích các quá trình và cơ chế hoạt động chức năng của các cơ quan và hệ thống trong cơ thể. Nếu giải phẫu học là "cái gì", thì sinh lý học là "hoạt động như thế nào" – từ cách tim đập, phổi trao đổi khí, đến cách tế bào thần kinh dẫn truyền xung điện.</p><h3>Lý giải & Ứng dụng</h3><p>Hiểu được tại sao các triệu chứng xuất hiện. Ví dụ, sinh lý học giải thích tại sao bệnh tiểu đường gây đi tiểu nhiều (do áp lực thẩm thấu của glucose trong nước tiểu). Đây là cơ sở để phát triển các phương pháp điều trị nhằm phục hồi hoặc điều chỉnh lại các chức năng bị rối loạn.</p>` },
      { id: 'hoa-sinh-y-hoc', name: 'Hóa Sinh Y Học (Biochemistry)', author: 'PGS. Trần Quốc Dũng', date: '16/10/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Phân tích các phản ứng hóa học diễn ra ở cấp độ phân tử bên trong tế bào, liên quan đến chuyển hóa năng lượng, vai trò của enzyme, vitamin, và sự điều hòa của hormon.</p><h3>Lý giải & Ứng dụng</h3><p>Là cơ sở của hầu hết các xét nghiệm máu và nước tiểu. Các chỉ số như đường huyết, mỡ máu (cholesterol), men gan (AST, ALT) đều là các chỉ số hóa sinh, phản ánh tình trạng hoạt động của cơ thể và giúp chẩn đoán, theo dõi bệnh tật.</p>` },
      { id: 'te-bao-hoc-di-truyen-hoc', name: 'Tế Bào & Di Truyền Học (Cell & Genetics)', author: 'BS. Đỗ Hoàng Lộc', date: '18/10/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Nghiên cứu cấu trúc và chức năng của tế bào, đơn vị cơ bản của sự sống, cùng với cơ chế di truyền thông qua gen (DNA). Môn học này giải thích cách thông tin di truyền được mã hóa, sao chép và biểu hiện.</p><h3>Lý giải & Ứng dụng</h3><p>Cực kỳ quan trọng trong chẩn đoán các bệnh di truyền (như hội chứng Down, bệnh máu khó đông), tư vấn tiền sản, và là nền tảng của y học cá thể hóa, giúp lựa chọn phương pháp điều trị dựa trên cấu trúc gen của từng bệnh nhân, đặc biệt trong ung thư học.</p>` },
      { id: 'vi-sinh-vat-y-hoc', name: 'Vi Sinh Vật Y Học (Microbiology)', author: 'ThS. Phạm Thị Mai', date: '20/10/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Tìm hiểu về các sinh vật siêu nhỏ như vi khuẩn, virus, nấm và ký sinh trùng có khả năng gây bệnh cho người. Môn học này bao gồm cách xác định, nuôi cấy và nghiên cứu đặc tính của chúng.</p><h3>Lý giải & Ứng dụng</h3><p>Là cơ sở để chẩn đoán các bệnh nhiễm trùng. Kết quả xét nghiệm vi sinh giúp bác sĩ xác định đúng tác nhân gây bệnh và lựa chọn kháng sinh phù hợp (làm kháng sinh đồ), từ đó phòng ngừa sự lây lan trong cộng đồng.</p>` },
      { id: 'mien-dich-hoc', name: 'Miễn Dịch Học (Immunology)', author: 'GS. Nguyễn Văn Lưu', date: '21/10/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Nghiên cứu về hệ thống phòng thủ của cơ thể (hệ miễn dịch) chống lại các tác nhân gây bệnh từ bên ngoài. Bao gồm cơ chế hoạt động của các tế bào miễn dịch, kháng thể và phản ứng viêm.</p><h3>Lý giải & Ứng dụng</h3><p>Là nền tảng của vắc-xin, giúp cơ thể tạo ra "trí nhớ miễn dịch". Miễn dịch học cũng giải thích các bệnh tự miễn (khi hệ miễn dịch tấn công chính cơ thể) và các phản ứng dị ứng, từ đó phát triển các liệu pháp điều trị tương ứng.</p>` },
      { id: 'benh-ly-hoc', name: 'Bệnh Lý Học (Pathology)', author: 'BSCKII. Trịnh Văn Hòa', date: '22/10/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Phân tích sự thay đổi về cấu trúc và chức năng của tế bào, mô, và cơ quan khi mắc bệnh. Đây là cầu nối giữa khoa học cơ bản và y học lâm sàng.</p><h3>Lý giải & Ứng dụng</h3><p>Là "tiêu chuẩn vàng" trong chẩn đoán nhiều bệnh, đặc biệt là ung thư. Bác sĩ bệnh lý học (giải phẫu bệnh) sẽ phân tích mẫu mô sinh thiết dưới kính hiển vi để xác định bản chất của tổn thương (lành tính hay ác tính), giúp đưa ra chẩn đoán cuối cùng.</p>` }
    ]
  },
  {
    title: "Kiến Thức Y Khoa Lâm Sàng",
    id: "lam-sang",
    subitems: [
      { id: 'trieu-chung-hoc', name: 'Triệu Chứng Học (Symptomatology)', author: 'BS. Lê Ngọc Hiền', date: '23/10/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Mô tả, phân loại và phân tích các biểu hiện chủ quan (triệu chứng, do bệnh nhân kể) và khách quan (dấu hiệu, do bác sĩ phát hiện) của bệnh tật. Ví dụ: đau, sốt, ho, vàng da, khó thở, sưng tấy.</p><h3>Lý giải & Ứng dụng</h3><p>Là bước đầu tiên và quan trọng nhất trong quá trình chẩn đoán. Bằng cách hỏi bệnh và phân tích triệu chứng một cách có hệ thống, bác sĩ có thể thu hẹp phạm vi các bệnh lý có thể xảy ra và chỉ định các xét nghiệm cần thiết, tránh lãng phí và chẩn đoán sai.</p>` },
      { id: 'chan-doan-benh', name: 'Chẩn Đoán Bệnh (Diagnostics)', author: 'TS. Đoàn Quang Phúc', date: '24/10/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Là một quy trình logic để xác định chính xác bệnh mà bệnh nhân đang mắc phải. Quá trình này bao gồm việc hỏi bệnh sử, khám thực thể, chỉ định và diễn giải kết quả xét nghiệm, hình ảnh học (X-quang, siêu âm, CT, MRI).</p><h3>Lý giải & Ứng dụng</h3><p>Một chẩn đoán chính xác là nền tảng cho một kế hoạch điều trị hiệu quả. Chẩn đoán phân biệt (loại trừ các bệnh có triệu chứng tương tự) là một kỹ năng quan trọng để tránh bỏ sót các bệnh lý nguy hiểm.</p>` },
      { id: 'dieu-tri-benh', name: 'Điều Trị Bệnh (Therapeutics)', author: 'BS. Nguyễn Ngọc Linh', date: '25/10/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Áp dụng các phương pháp can thiệp nhằm chữa khỏi bệnh, làm giảm triệu chứng, ngăn ngừa biến chứng hoặc phục hồi chức năng cho người bệnh. Bao gồm điều trị nội khoa (dùng thuốc), ngoại khoa (phẫu thuật), vật lý trị liệu, dinh dưỡng trị liệu...</p><h3>Lý giải & Ứng dụng</h3><p>Lựa chọn phương pháp điều trị phải dựa trên chẩn đoán chính xác, tình trạng cụ thể của bệnh nhân và các bằng chứng khoa học cập nhật nhất. Mục tiêu không chỉ là chữa bệnh mà còn là nâng cao chất lượng cuộc sống cho người bệnh.</p>` },
      { id: 'dich-te-hoc', name: 'Dịch Tễ Học (Epidemiology)', author: 'PGS. Bùi Thị Thu', date: '26/10/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Nghiên cứu về mô hình phân bố (ai, ở đâu, khi nào), tần suất và các yếu tố quyết định (nguyên nhân) của bệnh tật trong một quần thể dân cư.</p><h3>Lý giải & Ứng dụng</h3><p>Cung cấp bằng chứng cho y học dự phòng và xây dựng chính sách y tế. Dịch tễ học giúp xác định các yếu tố nguy cơ (như hút thuốc gây ung thư phổi), theo dõi sự bùng phát của dịch bệnh (như COVID-19), và đánh giá hiệu quả của các chương trình can thiệp cộng đồng.</p>` },
      { id: 'y-hoc-du-phong', name: 'Y Học Dự Phòng (Preventive Medicine)', author: 'ThS. Võ Văn Bình', date: '27/10/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Tập trung vào các biện pháp ngăn ngừa bệnh tật trước khi nó xảy ra (dự phòng cấp 1), phát hiện sớm bệnh để điều trị kịp thời (dự phòng cấp 2), và hạn chế biến chứng, phục hồi chức năng cho người đã mắc bệnh (dự phòng cấp 3).</p><h3>Lý giải & Ứng dụng</h3><p>Tiêm chủng là ví dụ điển hình của dự phòng cấp 1. Tầm soát ung thư cổ tử cung là dự phòng cấp 2. Phục hồi chức năng sau đột quỵ là dự phòng cấp 3. Y học dự phòng giúp giảm gánh nặng bệnh tật và tiết kiệm chi phí cho hệ thống y tế.</p>` },
      { id: 'suc-khoe-cong-dong', name: 'Sức Khỏe Cộng Đồng (Community Health)', author: 'BS. Đặng Mỹ Duyên', date: '28/10/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Quan tâm đến sức khỏe của cả một cộng đồng dân cư, xem xét các yếu tố xã hội, kinh tế, và môi trường ảnh hưởng đến sức khỏe. Mục tiêu là cải thiện sức khỏe và giảm bất bình đẳng về sức khỏe trong cộng đồng.</p><h3>Lý giải & Ứng dụng</h3><p>Các chương trình sức khỏe cộng đồng bao gồm giáo dục sức khỏe, cải thiện vệ sinh môi trường, đảm bảo an toàn thực phẩm, và cung cấp các dịch vụ y tế dễ tiếp cận cho các nhóm dân cư yếu thế.</p>` },
      { id: 'dao-duc-y-khoa', name: 'Đạo Đức Y Khoa (Medical Ethics)', author: 'GS. Trần Thị Hồng', date: '28/10/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Nêu ra các nguyên tắc và quy tắc đạo đức mà nhân viên y tế phải tuân thủ trong quá trình hành nghề. Bốn nguyên tắc cơ bản bao gồm: Tôn trọng quyền tự quyết của bệnh nhân, Làm điều thiện, Không làm điều ác, và Công bằng.</p><h3>Lý giải & Ứng dụng</h3><p>Hướng dẫn các quyết định khó khăn trong lâm sàng, chẳng hạn như quyền từ chối điều trị của bệnh nhân, bảo mật thông tin y tế, và phân bổ các nguồn lực y tế khan hiếm. Đạo đức y khoa đảm bảo mối quan hệ giữa thầy thuốc và bệnh nhân được xây dựng trên sự tin tưởng và tôn trọng.</p>` }
    ]
  },
  {
    title: "Thông Tin Y Tế Cụ Thể",
    id: "thong-tin-cu-the",
    subitems: [
      { id: 'thong-tin-ve-benh', name: 'Thông Tin Về Bệnh', author: 'Ban Biên Tập YKhoa.vn', date: '01/11/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Tập hợp và hệ thống hóa kiến thức chi tiết về một bệnh lý cụ thể, bao gồm định nghĩa, dịch tễ học, nguyên nhân, cơ chế bệnh sinh, triệu chứng, chẩn đoán, điều trị và các biện pháp phòng ngừa.</p><h3>Lý giải & Ứng dụng</h3><p>Là nguồn tài liệu tham khảo quan trọng cho cả nhân viên y tế và công chúng. Giúp người bệnh hiểu rõ hơn về tình trạng của mình, từ đó tuân thủ điều trị tốt hơn và chủ động tham gia vào quá trình chăm sóc sức khỏe.</p>` },
      { id: 'thong-tin-ve-thuoc', name: 'Thông Tin Về Thuốc', author: 'DS. Nguyễn Hồng Hà', date: '02/11/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Cung cấp thông tin chi tiết về một loại thuốc, bao gồm hoạt chất, dược lý (cơ chế tác dụng), chỉ định (dùng cho bệnh gì), chống chỉ định (không được dùng khi nào), liều dùng, cách dùng, tác dụng phụ và tương tác thuốc.</p><h3>Lý giải & Ứng dụng</h3><p>Đảm bảo việc sử dụng thuốc an toàn và hiệu quả. Dược sĩ và bác sĩ dựa vào đây để kê đơn, còn bệnh nhân dựa vào đây để sử dụng thuốc đúng cách, nhận biết và xử lý các tác dụng không mong muốn.</p>` },
      { id: 'thu-thuat-y-khoa', name: 'Thủ Thuật Y Khoa', author: 'BS. Trần Quang Tùng', date: '03/11/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Mô tả quy trình kỹ thuật của các can thiệp lâm sàng, từ đơn giản như tiêm, truyền dịch, đặt ống thông, đến phức tạp hơn như các thủ thuật trong hồi sức cấp cứu hay các ca phẫu thuật cơ bản.</p><h3>Lý giải & Ứng dụng</h3><p>Là cẩm nang hướng dẫn thực hành cho sinh viên y khoa và nhân viên y tế. Đối với bệnh nhân, việc hiểu rõ về thủ thuật sắp thực hiện giúp giảm bớt lo lắng và chuẩn bị tâm lý tốt hơn.</p>` },
      { id: 'cham-soc-suc-khoe-ca-nhan', name: 'Chăm Sóc Sức Khỏe Cá Nhân', author: 'CN. Dương Minh Anh', date: '04/11/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Cung cấp các hướng dẫn thực tiễn về việc tự theo dõi và cải thiện sức khỏe hàng ngày, bao gồm chế độ dinh dưỡng cân bằng, kế hoạch vận động thể chất phù hợp, vệ sinh giấc ngủ và các kỹ thuật quản lý căng thẳng.</p><h3>Lý giải & Ứng dụng</h3><p>Trao quyền cho mỗi cá nhân để trở thành người chủ động trong việc bảo vệ sức khỏe của chính mình. Áp dụng các kiến thức này giúp phòng ngừa hiệu quả các bệnh mãn tính không lây như tim mạch, tiểu đường, béo phì.</p>` },
      { id: 'dich-vu-y-te', name: 'Dịch Vụ Y Tế', author: 'Ban Biên Tập HealthZone', date: '05/11/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Cung cấp thông tin về hệ thống y tế, bao gồm danh bạ các bệnh viện, phòng khám theo chuyên khoa và địa điểm; thông tin về các gói bảo hiểm y tế và quyền lợi; cũng như các dịch vụ hỗ trợ bệnh nhân khác.</p><h3>Lý giải & Ứng dụng</h3><p>Giúp người dân dễ dàng tìm kiếm và tiếp cận các dịch vụ chăm sóc sức khỏe phù hợp với nhu cầu và khả năng tài chính của mình, đóng vai trò là cầu nối giữa người bệnh và hệ thống y tế.</p>` },
      { id: 'nghien-cuu-y-khoa', name: 'Nghiên Cứu Y Khoa', author: 'Viện Khoa học Sức khỏe Việt Nam', date: '06/11/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Cập nhật các kết quả, phát hiện và tiến bộ từ các công trình nghiên cứu y khoa mới nhất trên thế giới. Bao gồm các lĩnh vực tiên tiến như liệu pháp tế bào gốc, ứng dụng trí tuệ nhân tạo (AI) trong chẩn đoán, phát triển vắc-xin thế hệ mới, và các đột phá trong ung thư học.</p><h3>Lý giải & Ứng dụng</h3><p>Là động lực thúc đẩy y học không ngừng phát triển, mở ra những hy vọng và phương pháp điều trị mới cho các bệnh lý nan y, đồng thời cải tiến hiệu quả của các phương pháp điều trị hiện có.</p>` }
    ]
  },
  {
    title: "Sức Khỏe Số (Digital Health)",
    id: "suc-khoe-so",
    subitems: [
      { id: 'du-lieu-y-te-dien-tu', name: 'Dữ Liệu Y Tế Điện Tử (EHR/EMR)', author: 'CN. Nguyễn Thanh Quý', date: '07/11/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Hệ thống lưu trữ và quản lý thông tin sức khỏe của bệnh nhân dưới dạng kỹ thuật số, bao gồm lịch sử khám bệnh, kết quả xét nghiệm, đơn thuốc, và các ghi chú của bác sĩ. EHR/EMR cho phép chia sẻ thông tin liền mạch giữa các cơ sở y tế.</p><h3>Lý giải & Ứng dụng</h3><p>Cung cấp một cái nhìn toàn diện và liên tục về sức khỏe của bệnh nhân, giúp bác sĩ đưa ra quyết định lâm sàng chính xác hơn, giảm sai sót y khoa và tránh các xét nghiệm trùng lặp không cần thiết. Đây là "xương sống" của y tế hiện đại.</p>` },
      { id: 'ung-dung-suc-khoe', name: 'Ứng Dụng Sức Khỏe (Health Apps)', author: 'Trung tâm Sức khỏe Số Việt Nam', date: '08/11/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Giới thiệu các ứng dụng trên điện thoại thông minh hoặc máy tính bảng được thiết kế để theo dõi và quản lý sức khỏe cá nhân. Các ứng dụng này có thể theo dõi huyết áp, nhịp tim, giấc ngủ, lượng calo tiêu thụ, nhắc nhở uống thuốc, hoặc cung cấp các bài tập thể dục, thiền định.</p><h3>Lý giải & Ứng dụng</h3><p>Biến thiết bị cá nhân thành một trợ lý sức khỏe, giúp người dùng theo dõi các chỉ số quan trọng, xây dựng thói quen lành mạnh và chủ động hơn trong việc quản lý các bệnh mãn tính.</p>` },
      { id: 'thiet-bi-y-te-thong-minh', name: 'Thiết Bị Y Tế Thông Minh (Smart Devices)', author: 'TS. Lưu Hoàng Vũ', date: '09/11/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Các thiết bị đeo hoặc thiết bị y tế cá nhân có khả năng kết nối internet để thu thập và truyền dữ liệu sức khỏe theo thời gian thực. Ví dụ: đồng hồ thông minh đo ECG, SpO2; máy đo đường huyết liên tục; vòng tay theo dõi hoạt động.</p><h3>Lý giải & Ứng dụng</h3><p>Cho phép theo dõi sức khỏe liên tục ngay cả bên ngoài bệnh viện, giúp phát hiện sớm các dấu hiệu bất thường (như rung nhĩ) và cung cấp cho bác sĩ dữ liệu quý giá để theo dõi và điều chỉnh kế hoạch điều trị từ xa.</p>` },
      { id: 'y-hoc-tu-xa', name: 'Y Học Từ Xa (Telemedicine)', author: 'BS. Lý Hương Giang', date: '10/11/2025', content: `<h3>Kiến thức cốt lõi</h3><p>Mô hình cung cấp dịch vụ chăm sóc sức khỏe từ xa thông qua các công nghệ viễn thông như video call, ứng dụng chat, và các nền tảng trực tuyến. Bao gồm việc khám bệnh, tư vấn, hội chẩn, và theo dõi bệnh nhân tại nhà.</p><h3>Lý giải & Ứng dụng</h3><p>Phá bỏ rào cản địa lý, giúp bệnh nhân ở các vùng sâu vùng xa hoặc người già yếu, khó di chuyển có thể tiếp cận được dịch vụ y tế chất lượng. Nó cũng giúp tiết kiệm thời gian, chi phí đi lại và đặc biệt hữu ích trong các bối cảnh dịch bệnh.</p>` }
    ]
  }
];